Repository himedi3DHS/TN-project, pull requests merged in 2024-04, with the labels that each got.

#61 테스트화면 분리 완료
  database/create_dummy_datasource.sql
  src/main/java/com/_3dhs/tnproject/configuration/SpringSecurityConfiguration.java
  src/main/java/com/_3dhs/tnproject/main/MainController.java
  src/main/java/com/_3dhs/tnproject/member/dao/MemberMapper.java
  src/main/java/com/_3dhs/tnproject/member/dto/MemberDTO.java
  src/main/java/com/_3dhs/tnproject/member/service/AuthService.java
  src/main/java/com/_3dhs/tnproject/payment/controller/PaymentController.java
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/timeline/controller/TimelineController.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/timeline.css
  src/main/resources/static/js/pathFinder.js
  src/main/resources/templates/common/navigation.html
  src/main/resources/templates/common/profile.html
  src/main/resources/templates/error/denied.html
  src/main/resources/templates/manager/admin/list.html
  src/main/resources/templates/manager/member/list.html
  src/main/resources/templates/member/blockList.html
  src/main/resources/templates/payment/management.html
  src/main/resources/templates/timeline/list.html
  src/test/java/com/_3dhs/tnproject/member/dao/MemberMapperTests.java
Labels: Refector

#63 #53 관리 기록 조회 페이지 연동완료
  src/main/java/com/_3dhs/tnproject/manager/controller/ManagerController.java
  src/main/java/com/_3dhs/tnproject/manager/dao/ReportMapper.java
  src/main/java/com/_3dhs/tnproject/manager/dto/ReportDTO.java
  src/main/java/com/_3dhs/tnproject/manager/service/ReportService.java
  src/main/java/com/_3dhs/tnproject/member/dao/MemberMapper.java
  src/main/java/com/_3dhs/tnproject/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/ReportMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/common/testhub.html
  src/main/resources/templates/manager/admin/list.html
  src/main/resources/templates/manager/member/list.html
  src/main/resources/templates/manager/report/detail.html
  src/main/resources/templates/manager/report/list.html
  src/test/java/com/_3dhs/tnproject/member/dao/MemberMapperTests.java
Labels: New Fieature

#68 프로필 생성 로직 작성 완료
  src/main/java/com/_3dhs/tnproject/member/controller/MemberController.java
  src/main/java/com/_3dhs/tnproject/member/dao/MemberMapper.java
  src/main/java/com/_3dhs/tnproject/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/member/login.html
  src/test/java/com/_3dhs/tnproject/member/dao/MemberMapperTests.java
Labels: New Fieature, Refector

#71 #52 , #56 폴더 편집 페이지 기능 완료
  database/create_table.sql
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/dto/FolderDTO.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/static/js/folderEditEvent.js
  src/main/resources/templates/post/folder_edit.html
  src/main/resources/templates/post/main.html
Labels: New Fieature

#76 유료글 판단로직 PR
  database/create_table.sql
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
Labels: New Fieature

#80 Feature/67 비밀번호찾기
  src/main/java/com/_3dhs/tnproject/configuration/SpringSecurityConfiguration.java
  src/main/java/com/_3dhs/tnproject/member/controller/MemberController.java
  src/main/java/com/_3dhs/tnproject/member/dao/MemberMapper.java
  src/main/java/com/_3dhs/tnproject/member/service/MailService.java
  src/main/java/com/_3dhs/tnproject/member/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/js/memberEvent.js
  src/main/resources/templates/member/findPwd.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/regist.html
Labels: New Fieature

#87 feather#85 관리자/사이드바 링크걸기 완
  src/main/resources/templates/manager/admin/detail.html
  src/main/resources/templates/manager/admin/list.html
  src/main/resources/templates/manager/member/detail.html
  src/main/resources/templates/manager/member/list.html
  src/main/resources/templates/manager/report/detail.html
  src/main/resources/templates/manager/report/list.html
Labels: New Fieature

#90 검색엔진 환경설정
  build.gradle
  src/main/java/com/_3dhs/tnproject/TnProjectApplication.java
  src/main/java/com/_3dhs/tnproject/payment/dto/TissueDTO.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/java/com/_3dhs/tnproject/search/controller/SearchController.java
  src/main/java/com/_3dhs/tnproject/search/dao/DocumentMapper.java
  src/main/java/com/_3dhs/tnproject/test/TestController.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/common/login.html
  src/main/resources/templates/common/search_result.html
  src/main/resources/templates/common/testhub.html
  src/main/resources/templates/layout/common_layout.html
  src/main/resources/templates/member/regist.html
  src/main/resources/templates/payment/payment.html
  src/test/java/com/_3dhs/tnproject/post/dao/PostMapperTests.java
  src/test/java/com/_3dhs/tnproject/post/service/PostServiceTests.java
Labels: New Fieature, Test

#117 Feature/74 blog main select
  database/create_table.sql
  src/main/java/com/_3dhs/tnproject/member/dao/MemberMapper.java
  src/main/java/com/_3dhs/tnproject/member/service/MemberService.java
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/dto/PostDTO.java
  src/main/java/com/_3dhs/tnproject/post/dto/TabSearchDTO.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/static/js/blogMain.js
  src/main/resources/static/js/folderEditEvent.js
  src/main/resources/static/js/timeline.js
  src/main/resources/templates/post/folder_edit.html
  src/main/resources/templates/post/list.html
  src/main/resources/templates/post/main.html
  src/main/resources/templates/post/write.html
  src/main/resources/templates/timeline/list.html
  src/test/java/com/_3dhs/tnproject/post/dao/PostMapperTests.java
Labels: New Fieature

#124 #74
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/resources/static/js/folderEditEvent.js
  src/main/resources/templates/post/main.html
Labels: Bug Fix

#125 좋아요 버튼의 초기설정
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/LikeMapper.java
  src/main/java/com/_3dhs/tnproject/post/dto/PostDTO.java
  src/main/java/com/_3dhs/tnproject/post/service/LikeService.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/java/com/_3dhs/tnproject/timeline/controller/TimelineController.java
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/static/js/blogMain.js
  src/main/resources/static/js/timeline.js
  src/main/resources/templates/timeline/list.html
  src/test/java/com/_3dhs/tnproject/post/controller/PostControllerTests.java
Labels: Bug Fix

#127 추천글 알고리즘 PR
  src/main/java/com/_3dhs/tnproject/post/dao/LikeMapper.java
  src/main/java/com/_3dhs/tnproject/post/service/LikeService.java
  src/main/java/com/_3dhs/tnproject/timeline/controller/Recommend.java
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/static/js/pathFinder.js
  src/test/java/com/_3dhs/tnproject/timeline/RecommendTests.java
Labels: New Fieature

#130 Feature/72 post add editor add photo uploader
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/resources/static/js/write.js
  src/main/resources/templates/layout/common_layout.html
  src/main/resources/templates/post/folder_edit.html
  src/main/resources/templates/post/list.html
  src/main/resources/templates/post/main.html
  src/main/resources/templates/post/write.html
Labels: New Fieature

#136 차단목록 기능 pr
  src/main/java/com/_3dhs/tnproject/comments/dao/CommentsMapper.java
  src/main/java/com/_3dhs/tnproject/comments/service/CommentsService.java
  src/main/java/com/_3dhs/tnproject/member/controller/MemberController.java
  src/main/java/com/_3dhs/tnproject/member/dao/MemberMapper.java
  src/main/java/com/_3dhs/tnproject/member/service/MemberService.java
  src/main/resources/mappers/CommentsMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/js/blockListEvent.js
  src/main/resources/templates/member/blockList.html
  src/test/java/com/_3dhs/tnproject/member/dao/MemberMapperTests.java
  src/test/java/com/_3dhs/tnproject/post/dao/PostMapperTests.java
  src/test/java/com/_3dhs/tnproject/purchase/dao/PaymentMapperTests.java
Labels: New Fieature, View

#137 #89 관리자 CSS 정리 완료
  database/create_dummy_datasource.sql
  database/create_timelin_datasource.sql
  src/main/java/com/_3dhs/tnproject/common/paging/Pagenation.java
  src/main/java/com/_3dhs/tnproject/common/paging/SelectCriteria.java
  src/main/java/com/_3dhs/tnproject/configuration/SpringSecurityConfiguration.java
  src/main/java/com/_3dhs/tnproject/manager/controller/ManagerController.java
  src/main/java/com/_3dhs/tnproject/manager/dao/ReportMapper.java
  src/main/java/com/_3dhs/tnproject/manager/dto/PageDTO.java
  src/main/java/com/_3dhs/tnproject/manager/dto/ReportDTO.java
  src/main/java/com/_3dhs/tnproject/manager/model/ReportContents.java
  src/main/java/com/_3dhs/tnproject/manager/service/ReportService.java
  src/main/resources/mappers/ReportMapper.xml
  src/main/resources/static/css/admindetail.css
  src/main/resources/static/css/adminlist.css
  src/main/resources/static/css/memberDetail.css
  src/main/resources/static/css/memberlist.css
  src/main/resources/static/css/reportDetail.css
  src/main/resources/static/css/reportList.css
  src/main/resources/static/css/reportdetail.css
  src/main/resources/static/css/reportlist.css
  src/main/resources/templates/manager/admin/detail.html
  src/main/resources/templates/manager/admin/list.html
  src/main/resources/templates/manager/member/detail.html
  src/main/resources/templates/manager/member/list.html
  src/main/resources/templates/manager/member/report.html
  src/main/resources/templates/manager/report/detail.html
  src/main/resources/templates/manager/report/insertRC.html
  src/main/resources/templates/manager/report/list.html
Labels: New Fieature

#139 Feature/72 post add editor add photo uploader
  build.gradle
  database/create_table.sql
  files/image/84a9e746-61a0-4c21-9bfc-ade0c2e78acf_pngtree-three-puppies-with-their-mouths-open-are-posing-for-a-photo-image_2902292.jpg
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/dto/AttachmentDTO.java
  src/main/java/com/_3dhs/tnproject/post/dto/PostDTO.java
  src/main/java/com/_3dhs/tnproject/post/dto/PostTagDTO.java
  src/main/java/com/_3dhs/tnproject/post/dto/TagDTO.java
  src/main/java/com/_3dhs/tnproject/post/dto/WriteDTO.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/java/com/_3dhs/tnproject/post/util/FileUtil.java
  src/main/resources/application.yml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/static/js/blogMain.js
  src/main/resources/static/js/write.js
  src/main/resources/templates/post/main.html
  src/main/resources/templates/post/write.html
Labels: New Fieature

#144 상세보기 PR
  src/main/java/com/_3dhs/tnproject/common/aspect/PostServiceAspect.java
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/templates/common/search_result.html
  src/main/resources/templates/post/detail.html
Labels: New Fieature

#145 좋아요 한 목록 조회 PR
  src/main/java/com/_3dhs/tnproject/post/controller/PostController.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/js/blogMain.js
  src/test/java/com/_3dhs/tnproject/post/dao/PostMapperTests.java
  src/test/java/com/_3dhs/tnproject/post/service/PostServiceTests.java
Labels: View

#146 신규글 검색 index에 추가 PR
  src/main/java/com/_3dhs/tnproject/TnProjectApplication.java
  src/main/java/com/_3dhs/tnproject/common/aspect/PostServiceAspect.java
  src/main/java/com/_3dhs/tnproject/post/dao/PostMapper.java
  src/main/java/com/_3dhs/tnproject/post/service/PostService.java
  src/main/java/com/_3dhs/tnproject/search/controller/SearchController.java
  src/main/resources/mappers/PostMapper.xml
Labels: New Fieature

#152 #102 서브밋 버튼 완료
  src/main/java/com/_3dhs/tnproject/manager/controller/ManagerController.java
  src/main/java/com/_3dhs/tnproject/manager/dao/ReportMapper.java
  src/main/java/com/_3dhs/tnproject/manager/service/ReportService.java
  src/main/resources/mappers/ReportMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/manager/admin/detail.html
  src/main/resources/templates/manager/member/detail.html
  src/main/resources/templates/manager/report/detail.html
Labels: New Fieature
